name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      test-run:
        description: 'Run Tests (y/n)?'
        required: true
        default: 'y'

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      backend:
        image: eliasnogueira/combined-credit-api:latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -DskipTests -B package --file pom.xml

      - name: Run Health Check Tests
        run: mvn test -Dgroups="health"

      - name: Run Contract Tests
        run: mvn test -Dgroups="contract"

      - name: Run E2E Tests
        run: mvn test -Dgroups="e2e"

      - name: Run Functional Tests
        run: mvn test -Dgroups="functional"api/v1 -Dapi.port=443 -Dapi.health.context=/actuator